# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
forward_backward_fast <- function(pi, A, B, y, k, n, marginal_distr) {
    .Call('ensembleHMM_forward_backward_fast', PACKAGE = 'ensembleHMM', pi, A, B, y, k, n, marginal_distr)
}

#' @export
crossover <- function(x, y, t) {
    invisible(.Call('ensembleHMM_crossover', PACKAGE = 'ensembleHMM', x, y, t))
}

#' @export
crossover_mat <- function(X, Y, t, which_rows) {
    invisible(.Call('ensembleHMM_crossover_mat', PACKAGE = 'ensembleHMM', X, Y, t, which_rows))
}

#' @export
decimal_to_binary_mapping <- function(K) {
    .Call('ensembleHMM_decimal_to_binary_mapping', PACKAGE = 'ensembleHMM', K)
}

#' @export
hamming_ball <- function(index, radius, mapping) {
    .Call('ensembleHMM_hamming_ball', PACKAGE = 'ensembleHMM', index, radius, mapping)
}

#' @export
construct_all_hamming_balls <- function(radius, mapping) {
    .Call('ensembleHMM_construct_all_hamming_balls', PACKAGE = 'ensembleHMM', radius, mapping)
}

#' @export
ensemble_gaussian <- function(n_chains, y, alpha, k, n, max_iter, burnin, thin, estimate_marginals, fixed_pars, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, mu, sigma2, which_chains, subsequence, x) {
    .Call('ensembleHMM_ensemble_gaussian', PACKAGE = 'ensembleHMM', n_chains, y, alpha, k, n, max_iter, burnin, thin, estimate_marginals, fixed_pars, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, mu, sigma2, which_chains, subsequence, x)
}

#' @export
ensemble_discrete <- function(n_chains, y, alpha, k, s, n, max_iter, burnin, thin, estimate_marginals, fixed_pars, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, B, which_chains, subsequence) {
    .Call('ensembleHMM_ensemble_discrete', PACKAGE = 'ensembleHMM', n_chains, y, alpha, k, s, n, max_iter, burnin, thin, estimate_marginals, fixed_pars, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, B, which_chains, subsequence)
}

#' @export
ensemble_HMM <- function(n_chains, Y, mu, sigma, A, alpha, K, k, n, radius, max_iter, burnin, thin, estimate_marginals, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, which_chains, subsequence, x, nrows_crossover) {
    .Call('ensembleHMM_ensemble_HMM', PACKAGE = 'ensembleHMM', n_chains, Y, mu, sigma, A, alpha, K, k, n, radius, max_iter, burnin, thin, estimate_marginals, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, which_chains, subsequence, x, nrows_crossover)
}

