# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
forward_backward_fast <- function(pi, A, B, y, k, n, marginal_distr) {
    .Call('ensembleHMM_forward_backward_fast', PACKAGE = 'ensembleHMM', pi, A, B, y, k, n, marginal_distr)
}

#' @export
gibbs_sampling_fast_with_starting_vals <- function(pi0, A0, B0, y, alpha, k, s, n, max_iter, burnin, thin, marginal_distr, is_fixed_B) {
    .Call('ensembleHMM_gibbs_sampling_fast_with_starting_vals', PACKAGE = 'ensembleHMM', pi0, A0, B0, y, alpha, k, s, n, max_iter, burnin, thin, marginal_distr, is_fixed_B)
}

#' @export
gibbs_sampling_fast <- function(y, alpha, k, s, n, max_iter, burnin, thin, marginal_distr, is_fixed_B) {
    .Call('ensembleHMM_gibbs_sampling_fast', PACKAGE = 'ensembleHMM', y, alpha, k, s, n, max_iter, burnin, thin, marginal_distr, is_fixed_B)
}

#' @export
crossover <- function(x, y, n) {
    invisible(.Call('ensembleHMM_crossover', PACKAGE = 'ensembleHMM', x, y, n))
}

#' @export
double_crossover <- function(x, y, n) {
    invisible(.Call('ensembleHMM_double_crossover', PACKAGE = 'ensembleHMM', x, y, n))
}

#' @export
ensemble <- function(n_chains, y, alpha, k, s, n, max_iter, burnin, thin, estimate_marginals, is_fixed_B, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, n_crossovers, B, which_chains) {
    .Call('ensembleHMM_ensemble', PACKAGE = 'ensembleHMM', n_chains, y, alpha, k, s, n, max_iter, burnin, thin, estimate_marginals, is_fixed_B, parallel_tempering, crossovers, temperatures, swap_type, swaps_burnin, swaps_freq, n_crossovers, B, which_chains)
}

#' @export
hamming_distance <- function(X, n, m) {
    .Call('ensembleHMM_hamming_distance', PACKAGE = 'ensembleHMM', X, n, m)
}

